'use client';
import { createClient } from '@/lib/supabase-browser';import type { LibraryItem } from '@/lib/types';import { BookOpen, Search, Sparkles, UserRound, ArrowRight } from 'lucide-react';import { useEffect,useMemo,useState } from 'react';
type Mode='general'|'authors'|'books'|'free';type Rec={title:string;author:string;reason:string;type?:string};
export default function Recommendations(){const[recs,setRecs]=useState<Rec[]>([]);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[items,setItems]=useState<LibraryItem[]>([]);const[mode,setMode]=useState<Mode>('general');const[selected,setSelected]=useState<string[]>([]);const[filter,setFilter]=useState('');const[freeText,setFreeText]=useState('');
useEffect(()=>{void(async()=>{const{data}=await createClient().from('library_items').select('*').eq('status','read').order('updated_at',{ascending:false});setItems((data||[]) as LibraryItem[])})()},[]);const authors=useMemo(()=>[...new Set(items.flatMap(i=>i.book.authors||[]))].sort(),[items]);const choices=mode==='authors'?authors.map(name=>({id:name,label:name})):items.map(i=>({id:i.id,label:`${i.book.title} — ${i.book.authors.join(', ')}`}));const visible=choices.filter(c=>c.label.toLowerCase().includes(filter.toLowerCase()));
async function run(){setLoading(true);setError('');setRecs([]);const r=await fetch('/api/recommend',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,selected,freeText})});const j=await r.json();if(!r.ok)setError(j.error||'Não foi possível gerar.');else setRecs(j.recommendations||[]);setLoading(false)}
function searchBook(rec:Rec){location.href=`/buscar?q=${encodeURIComponent(`${rec.title} ${rec.author}`)}`}
return <main className="container section recommendation-page"><div className="eyebrow">Recomendação personalizada</div><h1>O que ler agora?</h1><p className="lead">Escolha os sinais que melhor representam seu gosto atual. A IA cruza suas notas e histórico sem limitar você ao que já conhece.</p>
<div className="recommend-mode-grid"><button className={`recommend-mode ${mode==='general'?'active':''}`} onClick={()=>{setMode('general');setSelected([])}}><Sparkles/><b>Gosto geral</b><span>Toda a biblioteca e suas notas.</span></button><button className={`recommend-mode ${mode==='authors'?'active':''}`} onClick={()=>{setMode('authors');setSelected([])}}><UserRound/><b>Por autores</b><span>Selecione autores que representam seu momento.</span></button><button className={`recommend-mode ${mode==='books'?'active':''}`} onClick={()=>{setMode('books');setSelected([])}}><BookOpen/><b>Por livros</b><span>Escolha obras específicas como referência.</span></button><button className={`recommend-mode ${mode==='free'?'active':''}`} onClick={()=>{setMode('free');setSelected([])}}><Search/><b>Pedido livre</b><span>Descreva exatamente o que deseja encontrar.</span></button></div>
{(mode==='authors'||mode==='books')&&<section className="ai-selection-panel"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder={mode==='authors'?'Pesquisar autor…':'Pesquisar livro lido…'}/><div className="ai-choice-list">{visible.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>setSelected(x=>x.includes(c.id)?x.filter(id=>id!==c.id):[...x,c.id])}/><span>{c.label}</span></label>)}</div><small>{selected.length} selecionado(s)</small></section>}
{mode==='free'&&<textarea className="ai-free-text" value={freeText} onChange={e=>setFreeText(e.target.value)} placeholder="Ex.: Quero um romance histórico menos melodramático, ambientado fora da Europa." rows={5}/>}<button className="primary-btn" onClick={run} disabled={loading||((mode==='authors'||mode==='books')&&!selected.length)||(mode==='free'&&!freeText.trim())}><Sparkles size={18}/>{loading?'Analisando…':'Gerar recomendações'}</button>{error&&<div className="form-error">{error}</div>}
{recs.length>0&&<section className="recommend-results">{recs.map((r,i)=><article className="recommend-card" key={`${r.title}-${i}`}><span className="recommend-index">0{i+1}</span><div><small>{r.type||(['Opção mais segura','Exploração próxima','Renovação de gosto'][i])}</small><h2>{r.title}</h2><p className="recommend-author">{r.author}</p><p>{r.reason}</p><button className="secondary-btn" onClick={()=>searchBook(r)}><Search size={17}/>Buscar este livro<ArrowRight size={16}/></button></div></article>)}</section>}</main>}
