import { createServerClient } from '@supabase/ssr';
import { cookies } from 'next/headers';
import { NextRequest, NextResponse } from 'next/server';
type Mode='general'|'authors'|'books'|'free';
type Row={id:string;status:string;read_count:number|null;rating:number|null;book:any};
type OR={choices?:Array<{message?:{content?:string|Array<{type?:string;text?:string}>}}> ;error?:{message?:string}};
function text(p:OR){const c=p.choices?.[0]?.message?.content;if(typeof c==='string')return c.trim();return Array.isArray(c)?c.map(x=>x.type==='text'?x.text||'':'').join('').trim():''}
function jsonFrom(raw:string){const cleaned=raw.replace(/^```json\s*/i,'').replace(/```$/,'').trim();try{return JSON.parse(cleaned)}catch{const a=cleaned.indexOf('['),b=cleaned.lastIndexOf(']');if(a>=0&&b>a)try{return JSON.parse(cleaned.slice(a,b+1))}catch{}return null}}
export async function POST(request:NextRequest){
 const apiKey=process.env.OPENROUTER_API_KEY;if(!apiKey)return NextResponse.json({error:'Adicione OPENROUTER_API_KEY nas variáveis da Vercel.'},{status:500});
 const body=await request.json().catch(()=>({}));const mode:Mode=body.mode||'general';const selected=Array.isArray(body.selected)?body.selected:[];const freeText=String(body.freeText||'').trim();
 const store=await cookies();const supabase=createServerClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,{cookies:{getAll:()=>store.getAll(),setAll:()=>undefined}});const{data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:'Faça login.'},{status:401});
 const{data,error}=await supabase.from('library_items').select('id,status,read_count,rating,book').eq('user_id',user.id).limit(300);if(error)return NextResponse.json({error:error.message},{status:500});const rows=(data||[]) as Row[];if(!rows.length)return NextResponse.json({error:'Adicione alguns livros antes.'},{status:400});
 const profile=rows.map(r=>({id:r.id,titulo:r.book?.title,autores:r.book?.authors||[],generos:r.book?.genres||[],paises:r.book?.authorCountries||[],nota:r.rating,status:r.status,vezesLido:r.read_count||1}));
 let focus='Use o perfil completo e dê maior peso às notas 4 e 5.';if(mode==='authors')focus=`Foque nestes autores: ${selected.join(', ')}.`;if(mode==='books')focus=`Foque nestes livros: ${JSON.stringify(profile.filter(x=>selected.includes(x.id)))}.`;if(mode==='free')focus=`Atenda a este pedido: ${freeText}`;
 const prompt=`Recomende exatamente 3 livros que NÃO estejam na biblioteca. ${focus}\nRetorne SOMENTE JSON válido, sem markdown, neste formato: [{"title":"...","author":"...","reason":"...","type":"Opção segura"}]. A segunda deve ser exploração próxima e a terceira renovação de gosto. Português do Brasil. Biblioteca: ${JSON.stringify(profile)}`;
 const response=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json','HTTP-Referer':process.env.NEXT_PUBLIC_SITE_URL||'https://books-gamma-woad.vercel.app','X-OpenRouter-Title':'Minha Estante'},body:JSON.stringify({model:process.env.OPENROUTER_MODEL||'openrouter/free',messages:[{role:'system',content:'Você é um bibliotecário preciso. Obedeça ao formato JSON.'},{role:'user',content:prompt}],temperature:.65,max_tokens:900}),cache:'no-store'});
 const payload=await response.json().catch(()=>null) as OR|null;if(!payload)return NextResponse.json({error:'Resposta inválida da OpenRouter.'},{status:502});if(!response.ok)return NextResponse.json({error:payload.error?.message||`OpenRouter indisponível (${response.status}).`},{status:502});const raw=text(payload);const recommendations=jsonFrom(raw);if(!Array.isArray(recommendations))return NextResponse.json({error:'A IA respondeu em formato inesperado. Tente novamente.'},{status:502});return NextResponse.json({recommendations:recommendations.slice(0,3)});
}
